# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv install
      # Step 3: run tests
      - run:
          name: run tests
          no_output_timeout: 30m
          command: |
            export PYTHONUNBUFFERED=1
            pipenv shell
            python3 manage.py test
      - store_artifacts:
                path: test-reports/
                destination: python_app
